version: "3.18"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ritik810
      MYSQL_DATABASE: blog_application
    networks:
      springboot-mysql-net:

  springboot-restful-webservice:
    container_name: springboot-restful-webservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8085"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
